import { type PieChartMainProps, type pieDataItem } from './types';
export declare const getPieChartMainProps: (props: PieChartMainProps) => {
    isThreeD: boolean | undefined;
    isBiggerPie: boolean | undefined;
    propData: pieDataItem[];
    data: pieDataItem[];
    itemHasInnerComponent: boolean;
    showInnerComponent: boolean;
    radius: number;
    canvasWidth: number;
    canvasHeight: number;
    shadowWidth: number;
    backgroundColor: string;
    shadowColor: string;
    semiCircle: boolean;
    pi: number;
    initialAngle: number;
    shadow: boolean;
    donut: boolean;
    strokeWidth: number;
    strokeColor: string;
    innerRadius: number;
    showText: boolean;
    textColor: string;
    textSize: number;
    tiltAngle: string;
    labelsPosition: import("..").LabelsPosition;
    showTextBackground: boolean;
    textBackgroundColor: string;
    showValuesAsLabels: boolean;
    showGradient: boolean;
    gradientCenterColor: string;
    toggleFocusOnPress: boolean;
    minShiftX: number;
    maxShiftX: number;
    minShiftY: number;
    maxShiftY: number;
    total: number;
    horizAdjustment: number;
    vertAdjustment: number;
    cx: number;
    cy: number;
    pData: number[];
    mData: number[];
    acc: number;
    paddingHorizontal: number;
    paddingVertical: number;
    extraRadiusForFocused: number;
};
